
file:
  savePath: /httx/logsDownload/
  names: ehuodiKA,ehuodiOpenApi
management:
  security:
    enabled: false
server:
  port: 8081
  context-path: /timed

regCenter:
  serverList: mt-zookeeper-vip:2181
  namespace: timed.regCenter

testSimpleJob:
#  cron: 0 0/10 * * * ?
  cron: 0 0 7 * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=test(无用参数?),1=test(2)

logDownLoadJob:
  cron: 0 0 8 * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=ehuodiKA,1=ehuodiOpenApi

logDueFileDeleteJob:
  cron: 0 0 1 * * ?
  shardingTotalCount: 2
  shardingItemParameters: 0=ehuodiKA,1=ehuodiOpenApi

dueFile:
  date: 14